import type { MealTemplate } from './types'

export const MEAL_TEMPLATES: MealTemplate[] = [
  // Breakfast
  {
    id: 'eggs-toast',
    name: 'Eggs & Toast',
    section: 'breakfast',
    keywords: ['eggs', 'bread'],
    calories: 380,
    protein: 28,
    tags: ['High Protein', 'Quick', 'Low Effort'],
  },
  {
    id: 'turkey-sausage-eggs',
    name: 'Turkey Sausage & Eggs',
    section: 'breakfast',
    keywords: ['turkey sausage', 'eggs'],
    calories: 420,
    protein: 35,
    tags: ['High Protein', 'Quick'],
  },
  {
    id: 'protein-shake-breakfast',
    name: 'Protein Shake Breakfast',
    section: 'breakfast',
    keywords: ['protein shake', 'fairlife'],
    calories: 240,
    protein: 42,
    tags: ['High Protein', 'Quick', 'Low Effort'],
  },
  {
    id: 'turkey-bacon-eggs',
    name: 'Turkey Bacon & Eggs',
    section: 'breakfast',
    keywords: ['turkey bacon', 'eggs'],
    calories: 350,
    protein: 30,
    tags: ['High Protein', 'Quick'],
  },

  // Lunch
  {
    id: 'chicken-rice-bowl',
    name: 'Chicken Rice Bowl',
    section: 'lunch',
    keywords: ['chicken', 'rice'],
    calories: 520,
    protein: 45,
    tags: ['High Protein', 'Meal Prep'],
  },
  {
    id: 'steak-potato',
    name: 'Steak & Potatoes',
    section: 'lunch',
    keywords: ['steak', 'potato'],
    calories: 580,
    protein: 42,
    tags: ['High Protein'],
  },
  {
    id: 'turkey-wrap',
    name: 'Turkey Deli Wrap',
    section: 'lunch',
    keywords: ['turkey deli', 'tortilla'],
    calories: 420,
    protein: 32,
    tags: ['Quick', 'Low Effort'],
  },
  {
    id: 'salmon-rice',
    name: 'Salmon & Rice',
    section: 'lunch',
    keywords: ['salmon', 'rice'],
    calories: 540,
    protein: 38,
    tags: ['High Protein', 'Meal Prep'],
  },
  {
    id: 'ground-turkey-pasta',
    name: 'Ground Turkey Pasta',
    section: 'lunch',
    keywords: ['ground turkey', 'pasta'],
    calories: 560,
    protein: 40,
    tags: ['High Protein', 'Meal Prep'],
  },

  // Dinner
  {
    id: 'lemon-pepper-chicken-rice',
    name: 'Lemon Pepper Chicken & Rice',
    section: 'dinner',
    keywords: ['chicken', 'rice', 'lemon pepper'],
    calories: 550,
    protein: 48,
    tags: ['High Protein', 'Meal Prep'],
  },
  {
    id: 'teriyaki-chicken-rice',
    name: 'Teriyaki Chicken & Rice',
    section: 'dinner',
    keywords: ['chicken', 'rice', 'teriyaki'],
    calories: 560,
    protein: 46,
    tags: ['High Protein', 'Meal Prep'],
  },
  {
    id: 'steak-sweet-potato',
    name: 'Steak & Sweet Potato',
    section: 'dinner',
    keywords: ['steak', 'sweet potato'],
    calories: 620,
    protein: 44,
    tags: ['High Protein'],
  },
  {
    id: 'salmon-potato',
    name: 'Salmon & Roasted Potatoes',
    section: 'dinner',
    keywords: ['salmon', 'potato'],
    calories: 580,
    protein: 40,
    tags: ['High Protein'],
  },
  {
    id: 'lean-beef-pasta',
    name: 'Lean Beef Pasta',
    section: 'dinner',
    keywords: ['lean ground beef', 'pasta'],
    calories: 600,
    protein: 42,
    tags: ['High Protein'],
  },

  // Snacks
  {
    id: 'jerky-snack',
    name: 'Jerky Snack',
    section: 'snacks',
    keywords: ['jerky'],
    calories: 120,
    protein: 15,
    tags: ['High Protein', 'Quick', 'Low Effort'],
  },
  {
    id: 'protein-shake-snack',
    name: 'Fairlife Protein Shake',
    section: 'snacks',
    keywords: ['fairlife', 'protein shake'],
    calories: 180,
    protein: 30,
    tags: ['High Protein', 'Quick', 'Low Effort'],
  },
  {
    id: 'popcorn-snack',
    name: 'Popcorn',
    section: 'snacks',
    keywords: ['popcorn'],
    calories: 150,
    protein: 4,
    tags: ['Quick', 'Low Effort'],
  },
  {
    id: 'rice-cakes-snack',
    name: 'Rice Cakes',
    section: 'snacks',
    keywords: ['rice cake'],
    calories: 70,
    protein: 2,
    tags: ['Quick', 'Low Effort'],
  },
  {
    id: 'turkey-deli-snack',
    name: 'Turkey Deli Roll-ups',
    section: 'snacks',
    keywords: ['turkey deli'],
    calories: 140,
    protein: 18,
    tags: ['High Protein', 'Quick', 'Low Effort'],
  },

  // Meal prep
  {
    id: 'prep-chicken-rice',
    name: 'Batch Chicken & Rice',
    section: 'meal_prep',
    keywords: ['chicken', 'rice'],
    calories: 520,
    protein: 45,
    tags: ['High Protein', 'Meal Prep'],
  },
  {
    id: 'prep-ground-turkey',
    name: 'Ground Turkey Prep Bowls',
    section: 'meal_prep',
    keywords: ['ground turkey', 'rice'],
    calories: 500,
    protein: 42,
    tags: ['High Protein', 'Meal Prep'],
  },
  {
    id: 'prep-steak-potato',
    name: 'Steak & Potato Meal Prep',
    section: 'meal_prep',
    keywords: ['steak', 'potato'],
    calories: 580,
    protein: 40,
    tags: ['High Protein', 'Meal Prep'],
  },
]
